using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace Gamestore.Services.Dto.PublishersDto;

/// <summary>
/// Represents a data transfer object for creating a publisher with detailed metadata information.
/// Used to provide comprehensive publisher information including company details and web presence.
/// </summary>
public class PublisherMetadataCreateRequestDto
{
    /// <summary>
    /// Gets or sets the unique identifier for the publisher.
    /// This field is ignored during JSON serialization as it's typically generated by the system.
    /// </summary>
    [JsonIgnore]
    public Guid Id { get; set; }

    /// <summary>
    /// Gets or sets the company name of the publisher.
    /// This field is required and should contain the official company name (e.g., "Electronic Arts", "Ubisoft").
    /// </summary>
    [Required]
    public string CompanyName { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the homepage URL of the publisher.
    /// This field is optional and should contain the publisher's official website URL.
    /// </summary>
    public string? HomePage { get; set; }

    /// <summary>
    /// Gets or sets the description of the publisher.
    /// This field is optional and can contain additional information about the publisher's history, focus, or business model.
    /// </summary>
    public string? Description { get; set; }
}