using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace Gamestore.Services.Dto.PlatformsDto;

/// <summary>
/// Represents a data transfer object for creating a new platform in the game store system.
/// Used to provide information required to create a gaming platform (e.g., PC, PlayStation, Xbox).
/// </summary>
public class PlatformCreateRequestDto
{
    /// <summary>
    /// Gets or sets the unique identifier for the platform.
    /// This field is ignored during JSON serialization as it's typically generated by the system.
    /// </summary>
    [JsonIgnore]
    public Guid Id { get; set; }

    /// <summary>
    /// Gets or sets the type or name of the platform to be created.
    /// This field is required and should specify the platform type (e.g., "PC", "PlayStation 5", "Xbox Series X").
    /// </summary>
    [Required]
    public string Type { get; set; } = string.Empty;
}
